# Generated by Django 5.2.6 on 2025-11-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseTempReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('node_id', models.CharField(max_length=64)),
                ('sensor_serial', models.CharField(max_length=64)),
                ('temp_c', models.FloatField()),
                ('recorded_at', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('local_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['sensor_serial', 'recorded_at'], name='temps_house_sensor__83c0cd_idx')],
                'unique_together': {('source', 'local_id')},
            },
        ),
    ]
